import Link from "next/link"

export const metadata = {
  title: 'Job portal',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "lightgray", padding: "5px"}}>Header
        </header>
        {children}
      <div>
        <ul>
          <li><Link href='/register'>Registration</Link></li>
            <li><Link href='/update'>Update</Link></li>
            <li><Link href='/delete'>Delete</Link></li>
        </ul>
      </div>
        <footer style={{backgroundColor: "lightgray", padding: "5px"}}>Footer</footer>
      </body>
      
    </html>
  )
}
