"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var student_1 = require("./student");
var teacher_1 = require("./teacher");
var course_1 = require("./course");
var teacher1 = new teacher_1.Teacher(1, 'Alamin sir');
var teacher2 = new teacher_1.Teacher(1, 'Anika mam');
var student1 = new student_1.default(102, 'Hrittika');
var student3 = new student_1.default(103, 'Tasnim');
var student2 = new student_1.default(101, 'Mrittika');
var course1 = new course_1.default(1, 'WebTech', teacher1);
course1.addStudent(student1);
course1.addStudent(student2);
var course2 = new course_1.default(2, 'OS', teacher2);
course2.addStudent(student1);
course2.addStudent(student3);
teacher1.addCourse(course1.courseName);
teacher2.addCourse(course2.courseName);
student1.enrollCourse(course1.courseName);
student1.enrollCourse(course2.courseName);
student3.enrollCourse(course1.courseName);
student2.enrollCourse(course2.courseName);
console.log(student1.toString());
student1.showCourses();
console.log(teacher1.toString());
teacher1.showCourses();
console.log(teacher2.toString());
teacher2.showCourses();
course1.showStudents();
course2.showStudents();
